spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.39.6:3306/share_platform?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: YmDFGTCikxmqC7LS